# Generated by Django 2.2.5 on 2019-09-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=50, verbose_name='Name')),
                ('asset_type', models.CharField(choices=[('Firewalls', 'Firewalls'), ('Routers', 'Routers'), ('Servers', 'Servers'), ('Storage', 'Storage'), ('Switches', 'Switches'), ('Workstations', 'Workstations')], max_length=15, verbose_name='Device Type')),
                ('asset_description', models.CharField(max_length=100, verbose_name='Description')),
                ('asset_env', models.CharField(choices=[('Dev', 'Development'), ('Test', 'Testing'), ('Prod', 'Production')], max_length=15, verbose_name='Environment')),
                ('asset_os', models.CharField(choices=[('CentOS 6', 'CentOS 6'), ('CentOS 7', 'CentOS 7'), ('RHEL 6', 'Red Hat Enterprise Linux 6'), ('RHEL 7', 'Red Hat Enterprise Linux 7'), ('Ubuntu 16.04', 'Ubuntu 16.04'), ('Ubuntu 18.04', 'Ubuntu 18.04'), ('Win 2008', 'Windows 2008'), ('Win 2012', 'Windows 2012'), ('Win 2016', 'Windows 2016'), ('Win 7', 'Windows 7'), ('Win 10', 'Windows 10'), ('Cisco IOS', 'Cisco IOS'), ('Extreme XOS', 'Extreme XOS'), ('Juniper JunOS', 'Juniper JunOS'), ('NA', 'None'), ('Other', 'Other'), ('VMware ESXi', 'VMware ESXi')], max_length=20, verbose_name='OS Name/Version')),
                ('asset_hardware', models.CharField(choices=[('Virtual', 'Virtual'), ('Physical', 'Physical')], max_length=15, verbose_name='Hardware: Virtual or Physical')),
            ],
        ),
    ]
